services:
  cs:
    container_name: cs
    image: evgeniyfimushkin/cs1.6:1.0
    build: .
    ports: 
      - "27016:27015/udp" # cs1.6 server
      - "27016:80/tcp" # http server running on 80
    environment:
      PORT: 27015
      HTTP_PORT: 27016 # game client will go to that port for files
      IP: 192.168.31.238
      MAP: "de_train"
    restart: always
