services:
  cs1.6:
    container_name: cs1.6
    image: evgeniyfimushkin/cs1.6:0.99
    ports: 
      - "8088:27015/udp"
      - "8088:80/tcp"
      - "8093:27025/udp"
    environment:
      PORT: 27015
      HTTP_PORT: 8088
      MAP: "de_train"
    restart: always
